/**
 * Runtime backend seam — Wish mikro-v2-prime-backend Group 1.
 *
 * The MCP server used to call `rlmLoop` directly; it now calls a backend.
 * That inversion is the whole point of this module: the server owns the
 * MCP contract (tools, sessions, result shape, progress presentation) and a
 * backend owns "what actually executes the turn", so a second engine can
 * slot in behind the same host-visible surface.
 *
 * Deliberately no `signal` parameter: the MCP server has no cancellation
 * wiring and `RLMOptions` (`src/rlm.ts`) has no `signal` field, so a signal
 * would have no producer and no legacy consumer. Each backend owns its own
 * stopping semantics — the legacy backend keeps its internal
 * `maxIterations`/`timeout` → `budgetHit` behavior; a future backend owns a
 * deadline/kill of its own.
 */

import type { MikroConfig } from "../config.js";
import type { LoadedContext } from "../context.js";
import type { Microagent } from "./agents.js";

/** Everything one backend needs to execute one delegated turn. */
export interface BackendRequest {
  /** The resume-folded prompt — the full text to run. */
  readonly query: string;
  /** Context loaded from the caller's `context:` argument, if any. */
  readonly context: LoadedContext | null;
  /** Config resolved for this run (`applyAgent` / model override applied). */
  readonly config: MikroConfig;
  /** Iteration cap implied by the agent's spec (`shape`/`budget`), if any. */
  readonly maxIterations?: number;
  /**
   * Provider-level cap for tokens generated by each root model call. This is
   * distinct from `config.budget.maxTokens`, which is a cumulative post-call
   * budget across input, output, and recursive children.
   */
  readonly maxOutputTokens?: number;
  /** Provider transport retries per root model call. Zero disables retries. */
  readonly maxRetries?: number;
  /**
   * Server working directory the turn runs against (`--dir` / the server's
   * cwd). The legacy backend has no use for it — context is already loaded
   * and rlmLoop runs in-process — but a subprocess backend must know where
   * the agent works: the prime backend maps it to prime-agent's `--cwd`.
   */
  readonly cwd: string;
  /**
   * Absolute path the caller's `context:` argument resolved to, when one was
   * passed. Lets a backend that needs real files (prime's `@file` arguments)
   * point at the caller's originals instead of the loaded snapshot.
   */
  readonly contextRoot?: string;
}

/**
 * The result of one backend run — exactly the fields the MCP layer consumes.
 *
 * Enumerated deliberately: `formatFooter` and `isFailedRun`
 * (`src/mcp/server.ts`) read `answer`, `iterations`, `budgetHit`,
 * `validationFailed`, and `usage.inputTokens` / `usage.outputTokens` /
 * `usage.totalCost`, and nothing else. A field beyond these would be dead
 * weight a backend must manufacture for nobody to read — which is why
 * `validationFailed` is listed here rather than merely tolerated: it has a
 * named reader (`formatFooter`'s footer segment), and a backend that cannot
 * produce it simply omits it.
 */
export interface MicroagentResult {
  readonly answer: string;
  readonly iterations: number;
  /** Matches `RLMResult.budgetHit`: `null` (or absent) when no budget fired. */
  readonly budgetHit?: string | null;
  /**
   * Mirrors `RLMResult.validation_failed` (camelCase here because this is an
   * internal seam, not a serialized wire shape): the answer above does not
   * match the pack's declared `VALIDATE.md` schema. This field is
   * legacy-backend-only today: the prime backends neither read
   * `config.validate` nor disclose it to the model, so they never set it —
   * not because they enforce that schema elsewhere. (`emit_done`'s parameter
   * schema comes from `config.output.schema`, a different declaration; a
   * `VALIDATE.md`-only pack running on prime is enforced by nothing.)
   * Extending validation to the prime backends is out of scope per the wish.
   */
  readonly validationFailed?: boolean;
  readonly usage: {
    readonly inputTokens: number;
    readonly outputTokens: number;
    readonly totalCost: number;
  };
}

/**
 * One execution backend: runs a single delegated turn to completion.
 *
 * `agent` is the resolved microagent — `undefined` for the generic
 * `mikro_query` tool, which has no agent spec. `request` carries the resolved
 * config and query; `emit` reports progress messages (without the tool label —
 * the server prefixes it) while the run executes. A throw is a *failed run*
 * the server reports as a tool error; the two designed non-throwing aborts
 * (empty responses, wall-clock timeout) must return normally so the server's
 * `isFailedRun` classification keeps working.
 */
export interface RuntimeBackend {
  run(
    agent: Microagent | undefined,
    request: BackendRequest,
    emit: (message: string) => void
  ): Promise<MicroagentResult>;
}
